### ISSUE TITLE
Add JS Routes Possibly 

### ISSUE THREAD

**Issue by tmartin314** [devato/inertia_phoenix#19]
Exploring the idea of adding a system for Phoenix routes in JS as they're so often used with frontend pages. 

Seems like it would be helpful but maybe it would over-complicate the purpose of this lib.

Curious to hear what others think.

**Comment by bigx333** [comment]
I actually started using inertia with the idea of just generating the routes on phoenix and exposing them as props but that approach gets old **really** quickly due to the amount of extra map manipulation you end up having to do for nested resources.

It seems that phoenix actually has no up-to-date libraries to expose routes in JS (none of them seems to work with the newer versions of plug), I ended up forking one of them and making a small change so it works: https://github.com/bigx333/phoenix_routes_js

While it is pretty much a must-have, exposing routes in JS has enough uses outside inertia to be its own package IMO

**Comment by tmartin314** [comment]
Thanks for the input @bigx333.  I'll take a look at your fork. 

Here's the main reasons I'm bringing it up:

- Reaching for a package to handle JS Routes seems inevitable for any non-trivial app built with inertia.   Just seems like it would ease the pain if it was handled with this integration.  

- There are likely going to be some unique quirks working with inertia or maybe not (you'd probably know more). 

- one lib to install and read about to get a full implementation going.

**Comment by totaltrash** [comment]
Just some thoughts:

> While it is pretty much a must-have, exposing routes in JS has enough uses outside inertia to be its own package IMO

Agree completely.

> one lib to install and read about to get a full implementation going

I think it depends on what approach you would take. The only JS route library I've used previously generates a JSON file in your assets, then the rest is up to the provided JS library.

If you're going to couple tightly to Inertia, you might need to provide separate adapters for each client adapter too (react, vue, etc)?

**Comment by tmartin314** [comment]
@totaltrash @bigx333 Good points.  Seems like it would be too much for this project. 

Closing for now.
